const test=require('node:test'), assert=require('node:assert/strict'), fs=require('node:fs');
const {JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(p,'utf8');
function env(){const dom=new JSDOM(read('writer-studio.html'),{url:'https://journal.test/',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;
 w.JOURNAL_CONFIG={SUPABASE_URL:'https://mock.test',SUPABASE_ANON_KEY:'mock'};w.matchMedia=()=>({matches:false,addEventListener(){}});w.eval(read('assets/elements.js'));
 let s=[...read('writer-studio.html').matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)].map(m=>m[1]).find(s=>s.includes('const Ed ='));
 s=s.slice(0,s.indexOf('(async function boot()'))+'window.studio={Ed,Elements,Sanitize,Tools,Pop,Dock,App,Model,UI,Save,Gutter};})();';w.eval(s);w.studio.Gutter.init();return {dom,w,...w.studio};}
test('mock catalog supports multiple tag terms and tiny vector files',()=>{const {dom,w}=env();assert.equal(w.JournalElements.search('romantic pink').length,2);assert.equal(w.JournalElements.search('unknown').length,0);for(const e of w.JournalElements.catalog)assert.ok(fs.statSync('.'+e.url).size<10240);dom.window.close()});
test('writer preserves approved decoration across serialization and reload, strips other images',()=>{const {dom,w,Ed,Sanitize}=env();Ed.mount();Ed.chapterId='c';Ed.el.innerHTML='<figure class="journal-element element-left element-wrap" style="width:24%" data-pid="paragraph_001"><img src="/assets/elements/mock-leaf.svg" onerror="evil()"></figure><p data-pid="paragraph_002">A poem</p><img src="https://bad.test/a.png">';
 const html=Ed.serialize();assert.match(html,/src="\/assets\/elements\/mock-leaf.svg"/);assert.ok(!html.includes('src="https://bad'));const box=w.document.createElement('div');box.append(Sanitize.toFragment(html,{keepIds:true}));assert.equal(box.querySelector('figure').style.width,'24%');assert.ok(box.querySelector('figure').classList.contains('element-wrap'));assert.equal(box.querySelector('[onerror]'),null);assert.equal(box.querySelectorAll('img').length,1);assert.equal(box.querySelector('p').dataset.pid,'paragraph_002');dom.window.close()});
test('picker search, insert, resize, wrap and remove run through the editor command',()=>{const {dom,w,Ed,Elements,Tools,App,Model,UI,Save}=env();
 Ed.mount();Ed.chapterId='c';Ed.el.innerHTML='<p data-pid="paragraph_001">Hello poem</p>';UI.mode='write';App.story={};Model.find=()=>({chapter:{status:'draft'}});App.locked=()=>false;Save.dirty=()=>{};Ed.afterInput=()=>{};Ed.placeCaret(Ed.el.firstChild,false);
 w.document.execCommand=(cmd,_,html)=>{assert.equal(cmd,'insertHTML');const r=w.getSelection().getRangeAt(0);r.deleteContents();const frag=r.createContextualFragment(html);r.insertNode(frag);return true};
 Tools.buildToolbar();const button=w.document.querySelector('#toolbar [aria-label="Elements"]');assert.equal(button.previousElementSibling.getAttribute('aria-label'),'More formatting');button.click();
 let search=w.document.querySelector('[aria-label="Search elements"]');search.value='botanical green';search.dispatchEvent(new w.Event('input'));assert.equal(w.document.querySelectorAll('.element-card').length,1);w.document.querySelector('.element-card').click();let figure=Ed.el.querySelector('figure');assert.ok(figure);assert.equal(Ed.el.querySelector('p').textContent,'Hello poem');
 Elements.edit(figure);const width=w.document.querySelector('[aria-label="Element width"]');width.value='22';const align=w.document.querySelector('[aria-label="Element placement"]');align.value='left';align.dispatchEvent(new w.Event('change'));w.document.querySelector('[aria-label="Wrap text"]').checked=true;[...w.document.querySelectorAll('.pop button')].find(b=>b.textContent==='Apply').click();figure=Ed.el.querySelector('figure');assert.equal(figure.style.width,'22%');assert.ok(figure.classList.contains('element-wrap'));Elements.edit(figure);[...w.document.querySelectorAll('.pop button')].find(b=>b.textContent==='Remove').click();assert.equal(Ed.el.querySelector('figure'),null);assert.equal(Ed.el.querySelector('p').textContent,'Hello poem');dom.window.close()});
test('reader-demo keeps placement safely; foreign decorations and active CSS are rejected',()=>{const {dom,w}=env();w.eval(read('assets/vendor/dompurify-3.4.16.min.js'));w.eval(read('assets/work-content.js'));const html=w.JournalContent.render('<figure class="journal-element element-right element-wrap" style="width:28%;position:fixed" onclick="evil()"><img src="/assets/elements/mock-stars.svg" onerror="evil()"></figure><p>Text</p>');const box=w.document.createElement('div');box.innerHTML=html;assert.equal(box.querySelector('figure').style.width,'28%');assert.equal(box.querySelector('figure').style.position,'');assert.equal(box.querySelector('[onclick],[onerror]'),null);assert.ok(box.querySelector('figure').classList.contains('element-wrap'));assert.ok(!w.JournalContent.render('<figure class="journal-element element-left"><img src="https://bad.test/a.png"></figure>').includes('<figure'));dom.window.close()});
test('structured reader retains elements alongside stable paragraph identities',()=>{const {dom,w}=env();const s=read('reader-studio.html');const a=s.indexOf('const PARSED=new Map()'),z=s.indexOf('function blocksOf(chId)',a);w.eval('const WRITER_BASE_PX=19,RE_ARA=/[\\u0600-\\u06ff]/;const pad3=n=>String(n).padStart(3,"0");'+s.slice(a,z)+'window.parseMock=parseChapter;');const b=w.parseMock('c','<figure class="journal-element element-left element-wrap" style="width:25%" data-pid="paragraph_001"><img src="/assets/elements/mock-heart.svg"></figure><p data-pid="paragraph_002">Text</p>');assert.equal(b[0].type,'element');assert.equal(b[0].pid,'paragraph_001');assert.equal(b[1].pid,'paragraph_002');dom.window.close()});
test('locked chapter does not allow element edits',()=>{const {dom,Ed,Elements,App,Model,UI}=env();Ed.mount();Ed.chapterId='c';UI.mode='write';App.story={};Model.find=()=>({chapter:{status:'published'}});App.locked=()=>true;assert.equal(Elements.commit('<p>bad</p>'),false);dom.window.close()});
