// Offline Chromium regression suite. Install Playwright and run: node tests/writer-elements.browser.cjs
const {chromium}=require('playwright');
const fs=require('fs');const assert=require('assert');const path=require('path');const root=path.join(__dirname,'..');
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE?{executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE}:{})});const context=await browser.newContext({viewport:{width:1200,height:900}});const page=await context.newPage();let errors=[];page.on('pageerror',e=>errors.push(e.message));
let html=fs.readFileSync(path.join(root,'writer-studio.html'),'utf8');const boot=html.indexOf('(async function boot()');html=html.slice(0,boot)+"window.__studio={Ed,App,UI,Store,Save,Model,Sanitize,Images,Elements,Tools,Dock,Panel,Gutter};\n})();\n</script></body></html>";
await page.route('**/*',async route=>{let url=new URL(route.request().url());if(url.pathname==='/writer-studio.html')return route.fulfill({contentType:'text/html',body:html});if(url.pathname==='/config.js')return route.fulfill({body:"window.JOURNAL_CONFIG={SUPABASE_URL:'https://example.test',SUPABASE_ANON_KEY:'test'};"});if(url.pathname.includes('supabase'))return route.fulfill({body:'window.supabase={createClient:()=>({})};'});let f={'/assets/elements.js':'elements.js','/assets/elements-editor.js':'elements-editor.js','/assets/elements.css':'elements.css','/assets/writer-drafts.js':'writer-drafts.js','/assets/design-view.js':'design-view.js'}[url.pathname];if(f)return route.fulfill({contentType:f.endsWith('.css')?'text/css':'application/javascript',body:fs.readFileSync(path.join(root,'assets',f),'utf8')});if(url.pathname.endsWith('.svg'))return route.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"><rect width="100" height="100" fill="green"/></svg>'});return route.abort();});
await page.goto('https://studio.test/writer-studio.html');await page.waitForFunction(()=>window.__studio);
const saved=await page.evaluate(async()=>{const {Ed,App,UI,Save,Model,Elements}=__studio;Save.dirty=()=>{};Save.flush=async()=>true;UI.syncToolbar=()=>{};__studio.Gutter.reset=()=>{};__studio.Gutter.update=()=>{};const s=Model.newStory();s.kind='poetry';const v=Model.newVolume(s),c=Model.newChapter(s);v.chapters=[c];s.volumes=[v];App.story=s;UI.mode='write';UI.applyKind();await Ed.load({id:c.id,storyId:s.id,html:'<p data-pid="verse_1">A long opening line with enough words to demonstrate that wrapping stays identical across every screen width and every reading device.</p><p data-pid="verse_2" style="text-align:center"><b>Second stanza stays beside its decoration.</b><br>Another carefully spaced line.</p>'});document.querySelector('#viewLibrary').classList.remove('on');document.querySelector('#viewStudio').classList.add('on');document.querySelector('#writeArea').hidden=false;Elements.insert({src:'/assets/elements/mock-leaf.svg',w:22,x:64});Elements.update({x:64,y:7,rotation:25,opacity:65,mode:'behind'});Elements.clear();return {html:Ed.serialize(),layout:Elements.layout};});
assert.equal(saved.layout.canvas.width,640);
const geometry=()=>page.evaluate(()=>{const root=__studio.Ed.el,r=root.getBoundingClientRect();return {width:r.width,text:Array.from(root.querySelectorAll('p')).map(p=>{const b=p.getBoundingClientRect();return {id:p.dataset.pid,x:b.x-r.x,y:b.y-r.y,w:b.width,h:b.height,text:p.textContent};}),element:__studio.Elements.figures().map(f=>{const b=f.querySelector('img').getBoundingClientRect();return {x:b.x-r.x,y:b.y-r.y,w:b.width,h:b.height};})};});
const authored=await geometry();await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{__studio.UI.applyMode();__studio.UI.syncViewport();__studio.Elements.render();});assert.deepEqual(await geometry(),authored,'writer canvas reflowed on mobile');
// Same saved HTML and renderer in the writer's actual preview.
await page.evaluate(()=>{__studio.UI.previewWidth='phone';__studio.UI.renderPreview();document.querySelector('#writeArea').hidden=true;document.querySelector('#preview').hidden=false;});assert.equal(await page.locator('#preview .je-design-controls').count(),1);
await page.waitForFunction(()=>document.querySelector('#preview .je-design-output')?.dataset.designScale);
const previewGeometry=await page.evaluate(()=>{const root=document.querySelector('#preview .je-design-output'),r=root.getBoundingClientRect(),scale=Number(root.dataset.designScale);return {text:Array.from(root.querySelectorAll('p')).map(p=>{const b=p.getBoundingClientRect();return {x:(b.x-r.x)/scale,y:(b.y-r.y)/scale,w:b.width/scale,h:b.height/scale};}),element:Array.from(root.querySelectorAll('.journal-element img')).map(img=>{const b=img.getBoundingClientRect();return {x:(b.x-r.x)/scale,y:(b.y-r.y)/scale,w:b.width/scale,h:b.height/scale};})};});
for(const group of ['text','element'])for(let i=0;i<authored[group].length;i++)for(const key of ['x','y','w','h'])assert(Math.abs(previewGeometry[group][i][key]-authored[group][i][key])<2,`writer preview ${group} ${key} moved`);
const reader=await context.newPage();let readerHTML=fs.readFileSync(path.join(root,'reader-demo.html'),'utf8').replace('boot();\n\n})();','window.__reader={renderPost,mountPage,S,goTo};\n\n})();');
await reader.route('**/*',async route=>{const u=new URL(route.request().url());if(u.pathname==='/reader-demo.html')return route.fulfill({contentType:'text/html',body:readerHTML});if(u.pathname==='/config.js')return route.fulfill({body:"window.JOURNAL_CONFIG={SUPABASE_URL:'https://example.test',SUPABASE_ANON_KEY:'test'};"});if(u.hostname==='cdn.jsdelivr.net')return route.fulfill({body:'window.supabase={createClient:()=>({})};'});if(u.pathname.endsWith('.svg'))return route.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"><rect width="100" height="100" fill="green"/></svg>'});const file=path.join(root,u.pathname);if(u.pathname.startsWith('/assets/')&&fs.existsSync(file))return route.fulfill({contentType:file.endsWith('.css')?'text/css':'application/javascript',body:fs.readFileSync(file,'utf8')});return route.abort();});
reader.on('pageerror',e=>errors.push(e.message));await reader.goto('https://studio.test/reader-demo.html');await reader.evaluate(saved=>{const post={id:'test-post',kind:'poem',type:'Poetry',title:'Designed poem',bodyMd:saved.html,author:'Author',username:'author',tags:[],comments:[],likes:0,date:'Today',read:'1 min',avatarColorHex:'#abcdef',grad:'linear-gradient(red,blue)',isOwn:true};const node=__reader.renderPost(post);document.querySelector('#pageFront').replaceChildren(node);},saved);
assert.equal(await reader.locator('#readerLayouts .je-design-controls').count(),1,'layout modes are not in header');
for(const width of [1200,768,390,320]){
 await reader.setViewportSize({width,height:850});await reader.waitForFunction(()=>document.querySelector('.je-design-output')?.dataset.designScale);
 await reader.evaluate(()=>JournalDesign.refresh(document.querySelector('.je-design-host')));await reader.waitForTimeout(50);
 const read=await reader.evaluate(()=>{const root=document.querySelector('.je-design-output'),r=root.getBoundingClientRect(),scale=Number(root.dataset.designScale);return {width:r.width/scale,text:Array.from(root.querySelectorAll('p')).map(p=>{const b=p.getBoundingClientRect();return {id:p.dataset.pid,x:(b.x-r.x)/scale,y:(b.y-r.y)/scale,w:b.width/scale,h:b.height/scale,text:p.textContent};}),element:Array.from(root.querySelectorAll('.journal-element img')).map(img=>{const b=img.getBoundingClientRect();return {x:(b.x-r.x)/scale,y:(b.y-r.y)/scale,w:b.width/scale,h:b.height/scale};}),scale};});
 assert(Math.abs(read.width-authored.width)<1);for(let i=0;i<authored.text.length;i++)for(const key of ['x','y','w','h'])assert(Math.abs(read.text[i][key]-authored.text[i][key])<2,`${width} paragraph ${i} ${key} moved`);for(const key of ['x','y','w','h'])assert(Math.abs(read.element[0][key]-authored.element[0][key])<2,`${width} element ${key} moved`);
 const framing=await reader.evaluate(()=>{const book=document.querySelector('#bookWrap').getBoundingClientRect(),canvas=document.querySelector('.je-design-stage').getBoundingClientRect(),viewport=document.querySelector('.je-design-viewport').getBoundingClientRect();return {width:book.width,screen:innerWidth,center:Math.abs((canvas.left+canvas.right)-(viewport.left+viewport.right)),margin:canvas.left,overflow:getComputedStyle(document.querySelector('.je-design-viewport')).overflowY,coverRatio:(()=>{const b=document.querySelector('.cover').getBoundingClientRect();return b.width/b.height;})(),coverHeight:document.querySelector('.cover').getBoundingClientRect().height,landscape:matchMedia('(min-width:700px) and (orientation:landscape)').matches,height:innerHeight,title:getComputedStyle(document.querySelector('h1.title')).textAlign};});
 assert.equal(framing.width,framing.screen,'reader does not fill screen');assert(framing.margin>=16,'design has no side margin');assert.equal(framing.title,'center');if(framing.landscape)assert(Math.abs(framing.coverHeight/framing.height-.4)<.01,'landscape cover is not 40% height');else assert(Math.abs(framing.coverRatio-1.5)<.01,'portrait cover lost 3:2 aspect ratio');assert(framing.center<2,'canvas stuck to left');assert.equal(framing.overflow,'visible','nested viewport traps scroll');
 // Core's asynchronous refresh must not calculate geometry against an already scaled canvas.
 await reader.evaluate(()=>JournalElements.refresh());await reader.waitForTimeout(40);
}
// Page-turn transforms on an ancestor must not alter saved layout geometry.
const beforeTurn=await reader.evaluate(()=>{const root=document.querySelector('.je-design-output');return {height:root.style.getPropertyValue('--je-page-height'),elements:Array.from(root.querySelectorAll('.journal-element')).map(f=>[f.style.top,f.style.left,f.style.width])};});await reader.evaluate(()=>{document.querySelector('.je-design-host').style.transform='perspective(1000px) rotateY(35deg)';JournalElements.refresh();});await reader.waitForTimeout(50);const duringTurn=await reader.evaluate(()=>{const root=document.querySelector('.je-design-output');return {height:root.style.getPropertyValue('--je-page-height'),elements:Array.from(root.querySelectorAll('.journal-element')).map(f=>[f.style.top,f.style.left,f.style.width])};});assert.deepEqual(duringTurn,beforeTurn,'page-turn transform changed element coordinates');await reader.evaluate(()=>document.querySelector('.je-design-host').style.transform='');
await reader.getByRole('button',{name:'Reading view',exact:true}).click();assert(await reader.locator('.je-reading-output').isVisible());assert.equal(await reader.locator('.je-reading-output .journal-element').count(),0);assert((await reader.locator('.je-reading-output').textContent()).includes('Second stanza'));await reader.getByRole('button',{name:'Original layout',exact:true}).click();assert.equal(await reader.getByRole('button',{name:/Zoom|Fit page/}).count(),0);
// Exercise the real scrolling surface, header, and preserved default Shayari alignment.
await reader.evaluate(()=>{const core=JournalElements,box=document.createElement('div');box.append(core.makeLayout(document,{canvas:{width:640,font:'serif',size:22,line:1.85,gap:0,align:'center'}}));box.insertAdjacentHTML('beforeend',Array.from({length:70},(_,i)=>'<p data-pid="line_'+i+'">A verse that stays centered on its own page '+i+'</p>').join(''));box.append(core.make(document,{src:core.catalog[0].url,floating:true,mode:'front',anchor:'paragraph',anchorId:'line_8',x:65,y:2,w:15}));window.testPost={id:'scroll-post',kind:'short',type:'Shayari',title:'Long Shayari',bodyMd:box.innerHTML,author:'Author',username:'author',tags:[],comments:[],likes:0,date:'Today',read:'1 min',avatarColorHex:'#abcdef',grad:'linear-gradient(red,blue)',isOwn:true};__reader.mountPage(document.querySelector('#pageFront'),testPost,'front');__reader.S.nextRef={id:'unrequested-next'};});
await reader.waitForFunction(()=>document.querySelector('.je-design-output')?.dataset.designScale);
assert.equal(await reader.locator('.je-design-output').evaluate(n=>getComputedStyle(n).textAlign),'center');
await reader.locator('.page-scroll').evaluate(n=>n.scrollTop=380);
await reader.mouse.move(160,420);await reader.mouse.wheel(0,300);await reader.waitForTimeout(120);
assert(await reader.locator('.page-scroll').evaluate(n=>n.scrollTop>380),'wheel over design did not scroll page');
const cdp=await context.newCDPSession(reader);await cdp.send('Emulation.setTouchEmulationEnabled',{enabled:true});
const touchStart=await reader.locator('.page-scroll').evaluate(n=>n.scrollTop);
await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:160,y:600}]});
for(const y of [570,530,480,420,360]){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:160,y}]});await reader.waitForTimeout(16);}
await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await reader.waitForTimeout(120);
assert(await reader.locator('.page-scroll').evaluate(n=>n.scrollTop)>touchStart,'vertical touch over design did not scroll');
await reader.locator('.page-scroll').evaluate(n=>n.scrollTop=n.scrollHeight);await reader.mouse.wheel(0,150);await reader.waitForTimeout(120);assert.equal(await reader.locator('h1.title').textContent(),'Long Shayari','vertical scroll turned to another post');
await reader.getByRole('button',{name:'Reading view',exact:true}).click();assert(await reader.locator('.je-reading-output').isVisible());
await reader.locator('.page-scroll').evaluate(n=>n.scrollTop=0);await reader.getByRole('button',{name:'Reading theme',exact:true}).click();await reader.getByRole('button',{name:'Dark Paper',exact:true}).click();assert.equal(await reader.locator('html').getAttribute('data-theme'),'dark');await reader.getByRole('button',{name:'Reading theme',exact:true}).click();
await reader.getByRole('button',{name:'Original layout',exact:true}).click();await reader.screenshot({path:'/tmp/reader-mobile.png'});
// The cover header overlays the real 3:2 image and remains usable on scroll.
await reader.locator('.page-scroll').evaluate(n=>n.scrollTop=0);await reader.waitForTimeout(30);
assert(await reader.locator('.topbar').evaluate(n=>n.classList.contains('over-cover')),'header is not over cover');
const coverLayout=await reader.evaluate(()=>{const cover=document.querySelector('.cover').getBoundingClientRect(),head=document.querySelector('.topbar').getBoundingClientRect(),label=document.querySelector('.type-chip').getBoundingClientRect();return {ratio:cover.width/cover.height,overlay:head.top>=cover.top&&head.bottom<cover.bottom,label:cover.bottom-label.bottom,left:label.left-cover.left,background:getComputedStyle(document.querySelector('.topbar')).backgroundColor};});
assert(Math.abs(coverLayout.ratio-1.5)<.01);assert(coverLayout.overlay);assert(coverLayout.label>=15&&coverLayout.label<=17);assert.equal(coverLayout.background,'rgba(0, 0, 0, 0)');
// Real pinch zoom, followed by horizontal and vertical touch panning.
await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:110,y:400},{x:210,y:400}]});
for(const d of [120,150,180,220]){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:160-d/2,y:400},{x:160+d/2,y:400}]});await reader.waitForTimeout(16);}
await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await reader.waitForTimeout(60);
assert(await reader.locator('.page-scroll').evaluate(n=>n.classList.contains('reader-zoomed')),'pinch did not zoom');assert(await reader.evaluate(()=>JournalReaderView.isZoomed()));
const panBefore=await reader.locator('.page-scroll').evaluate(n=>({x:n.scrollLeft,y:n.scrollTop,width:n.scrollWidth,height:n.scrollHeight}));
await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:230,y:650}]});
for(const n of [1,2,3,4,5]){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:230-n*20,y:650}]});await reader.waitForTimeout(16);}
await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await reader.waitForTimeout(100);
const panAfter=await reader.locator('.page-scroll').evaluate(n=>({x:n.scrollLeft,y:n.scrollTop,width:n.scrollWidth,height:n.scrollHeight}));assert(panAfter.x>panBefore.x+20,'zoomed touch cannot pan horizontally '+JSON.stringify({panBefore,panAfter}));await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:160,y:650}]});for(const n of [1,2,3,4,5]){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:160,y:650-n*30}]});await reader.waitForTimeout(16);}await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await reader.waitForTimeout(100);assert(await reader.locator('.page-scroll').evaluate(n=>n.scrollTop)>panBefore.y+20,'zoomed touch cannot pan vertically');assert.equal(panAfter.height,panBefore.height,'zoom caused runaway content height');
await reader.keyboard.press('ArrowRight');await reader.evaluate(()=>__reader.goTo(1));assert.equal(await reader.evaluate(()=>__reader.S.state),'idle','zoomed reader tried to turn page');
await reader.locator('.page-scroll').evaluate(n=>{n.scrollLeft=100;n.scrollTop=600;});await reader.mouse.move(240,500);await reader.mouse.down();await reader.mouse.move(150,410,{steps:6});await reader.mouse.up();assert.equal(await reader.evaluate(()=>__reader.S.state),'idle');assert(await reader.locator('.page-scroll').evaluate(n=>n.scrollLeft>150&&n.scrollTop>650),'mouse drag cannot pan in both directions');
await reader.keyboard.press('Escape');await reader.waitForTimeout(50);assert.equal(await reader.evaluate(()=>JournalReaderView.isZoomed()),false);assert.equal(await reader.locator('.page-scroll').evaluate(n=>n.scrollLeft),0);
// Ctrl-wheel zoom uses the same pan surface and clamps zoom-out at Fit Page.
await reader.mouse.move(160,400);await reader.keyboard.down('Control');await reader.mouse.wheel(0,-100);await reader.keyboard.up('Control');assert(await reader.evaluate(()=>JournalReaderView.isZoomed()));
await reader.keyboard.down('Control');await reader.mouse.wheel(0,100);await reader.mouse.wheel(0,100);await reader.keyboard.up('Control');await reader.waitForTimeout(50);assert.equal(await reader.evaluate(()=>JournalReaderView.isZoomed()),false);
// Zoom-out pinch returns to the original scale, without a page turn.
await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:110,y:400},{x:210,y:400}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:60,y:400},{x:260,y:400}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert(await reader.evaluate(()=>JournalReaderView.isZoomed()));
await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:50,y:400},{x:270,y:400}]});for(const d of [200,170,140,100]){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:160-d/2,y:400},{x:160+d/2,y:400}]});await reader.waitForTimeout(16);}await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.equal(await reader.evaluate(()=>JournalReaderView.isZoomed()),false);assert.equal(await reader.evaluate(()=>__reader.S.state),'idle');
await reader.keyboard.press('Control+=');assert(await reader.evaluate(()=>JournalReaderView.isZoomed()));await reader.keyboard.press('Control+0');assert.equal(await reader.evaluate(()=>JournalReaderView.isZoomed()),false);
// Native viewport zoom (e.g. pinching outside the post) also disables every turn path.
await cdp.send('Emulation.setPageScaleFactor',{pageScaleFactor:2});await reader.waitForTimeout(40);await reader.evaluate(()=>__reader.goTo(1));assert.equal(await reader.evaluate(()=>__reader.S.state),'idle');await cdp.send('Emulation.setPageScaleFactor',{pageScaleFactor:1});await reader.waitForTimeout(40);assert.equal(await reader.evaluate(()=>JournalReaderView.isZoomed()),false);
// Page-turn dragging is available again only at Fit Page.
await reader.locator('.page-scroll').evaluate(n=>n.scrollTop=0);await reader.mouse.move(200,140);await reader.mouse.down();await reader.mouse.move(160,140,{steps:4});assert.equal(await reader.evaluate(()=>__reader.S.state),'dragging');await reader.mouse.up();await reader.waitForTimeout(300);assert.equal(await reader.evaluate(()=>__reader.S.state),'idle');
// Switching to a long-form teaser clears header modes without touching its reading link.
await reader.evaluate(()=>__reader.mountPage(document.querySelector('#pageFront'),{...testPost,isTeaser:true,kind:'long',type:'Journal',teaserExcerpt:'<p>A journal description.</p>',readWholeLabel:'Read whole journal'},'front'));assert(await reader.locator('#readerLayouts').isHidden());assert(await reader.getByRole('link',{name:'Read whole journal',exact:true}).isVisible());
await reader.setViewportSize({width:1200,height:850});await reader.screenshot({path:'/tmp/reader-desktop-cover.png'});
// Older posts without canvas metadata must still expose both reader modes.
await reader.evaluate(()=>{const host=document.createElement('div');host.className='article poetry';host.innerHTML='<p>An older poem, with no canvas marker.</p>';document.querySelector('#pageFront').replaceChildren(host);JournalDesign.mount(host,{controlsHost:document.querySelector('#readerLayouts')});if(document.querySelectorAll('#readerLayouts .je-design-controls button').length!==2)throw Error('legacy controls missing');if(!host.querySelector('.je-design-legacy-note'))throw Error('legacy layout uncertainty was hidden');});await reader.getByRole('button',{name:'Reading view',exact:true}).click();assert((await reader.locator('.je-reading-output').textContent()).includes('An older poem'));
// Long-form works reject new Elements; existing decorations still survive save/reload.
await page.evaluate(async html=>{const {Ed,App,Elements}=__studio;App.story.kind='journal';await Ed.load({id:Ed.chapterId,storyId:Ed.storyId,html});const count=Elements.items.size;if(Elements.allowed()||Elements.insert({src:'/assets/elements/mock-leaf.svg'})!==false)throw Error('long-form elements enabled');if(Elements.items.size!==count||!Ed.serialize().includes('mock-leaf'))throw Error('legacy decoration lost');},saved.html);
// Loading a new document captures its own defaults, not the previous canvas metrics.
await page.evaluate(async()=>{const {Ed,App,UI,Elements}=__studio;App.story.kind='shayari';UI.mode='write';UI.applyKind();await Ed.load({id:Ed.chapterId,storyId:Ed.storyId,html:'<p>New Shayari</p>'});if(Elements.layout.canvas.align!=='center')throw Error('Shayari default alignment lost');App.story.kind='poetry';UI.applyKind();await Ed.load({id:Ed.chapterId,storyId:Ed.storyId,html:'<p>New poem</p>'});if(Elements.layout.canvas.align==='center')throw Error('Previous post alignment leaked into new poem');});
// A page canvas with margins and a paragraph anchor must match the actual writer preview.
await page.evaluate(async()=>{const {Ed,App,UI,Elements}=__studio;App.story.kind='shayari';UI.mode='write';UI.applyKind();document.querySelector('#preview').hidden=true;document.querySelector('#writeArea').hidden=false;const box=document.createElement('div');box.append(JournalElements.makeLayout(document,{mode:'page',paper:'A5',margin:15,canvas:{width:640,font:'serif',size:22,line:1.85,gap:0,align:'center'}}));box.insertAdjacentHTML('beforeend','<p data-pid="anchor_one">First verse with some text</p><p data-pid="anchor_two">Second verse<br>Another line</p>');await Ed.load({id:Ed.chapterId,storyId:Ed.storyId,html:box.innerHTML});Elements.insert({src:'/assets/elements/mock-flower.svg'});Elements.update({anchor:'paragraph',anchorId:'anchor_two',x:55,y:8,w:20,rotation:35,mode:'front'});Elements.clear();});
const pageAuthored=await geometry();await page.evaluate(()=>{__studio.UI.renderPreview();document.querySelector('#writeArea').hidden=true;document.querySelector('#preview').hidden=false;});await page.waitForFunction(()=>document.querySelector('#preview .je-design-output')?.dataset.designScale);
const pagePreview=await page.evaluate(()=>{const root=document.querySelector('#preview .je-design-output'),r=root.getBoundingClientRect(),scale=Number(root.dataset.designScale);return {text:Array.from(root.querySelectorAll('p')).map(p=>{const b=p.getBoundingClientRect();return {x:(b.x-r.x)/scale,y:(b.y-r.y)/scale,w:b.width/scale,h:b.height/scale};}),element:Array.from(root.querySelectorAll('.journal-element img')).map(img=>{const b=img.getBoundingClientRect();return {x:(b.x-r.x)/scale,y:(b.y-r.y)/scale,w:b.width/scale,h:b.height/scale};}),align:getComputedStyle(root).textAlign};});assert.equal(pagePreview.align,'center');
for(const group of ['text','element'])for(let i=0;i<pageAuthored[group].length;i++)for(const key of ['x','y','w','h'])assert(Math.abs(pagePreview[group][i][key]-pageAuthored[group][i][key])<2,`page preview ${group} ${key} moved: ${pagePreview[group][i][key]} vs ${pageAuthored[group][i][key]}`);
await page.getByRole('button',{name:'Desktop',exact:true}).click();assert(await page.locator('#preview .reader').evaluate(n=>n.classList.contains('k-shayari')),'preview device switch dropped category');
assert.equal(errors.length,0,errors.join('\n'));console.log('Fixed design: writer and real reader geometry preserved at 1200/768/390/320px; view modes, fit, preview, category gating and legacy preservation passed.');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
