// Offline Chromium regression suite. Install Playwright and run: node tests/writer-elements.browser.cjs
const {chromium}=require('playwright');
const fs=require('fs');const assert=require('assert');const path=require('path');const root=path.join(__dirname,'..');
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE?{executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE}:{})});const context=await browser.newContext({viewport:{width:1200,height:900}});const page=await context.newPage();let errors=[];page.on('pageerror',e=>errors.push(e.message));
let html=fs.readFileSync(path.join(root,'writer-studio.html'),'utf8');const boot=html.indexOf('(async function boot()');html=html.slice(0,boot)+"window.__studio={Ed,App,UI,Store,Save,Model,Sanitize,Images,Elements,Tools,Dock,Panel,Gutter};\n})();\n</script></body></html>";
await page.route('**/*',async route=>{let url=new URL(route.request().url());if(url.pathname==='/writer-studio.html')return route.fulfill({contentType:'text/html',body:html});if(url.pathname==='/config.js')return route.fulfill({body:"window.JOURNAL_CONFIG={SUPABASE_URL:'https://example.test',SUPABASE_ANON_KEY:'test'};"});if(url.pathname.includes('supabase'))return route.fulfill({body:'window.supabase={createClient:()=>({})};'});let f={'/assets/elements.js':'elements.js','/assets/elements-editor.js':'elements-editor.js','/assets/elements.css':'elements.css','/assets/writer-drafts.js':'writer-drafts.js','/assets/design-view.js':'design-view.js'}[url.pathname];if(f)return route.fulfill({contentType:f.endsWith('.css')?'text/css':'application/javascript',body:fs.readFileSync(path.join(root,'assets',f),'utf8')});if(url.pathname.endsWith('.svg'))return route.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"><rect width="100" height="100" fill="green"/></svg>'});return route.abort();});
await page.goto('https://studio.test/writer-studio.html');await page.waitForFunction(()=>window.__studio);
const saved=await page.evaluate(async()=>{const {Ed,App,UI,Save,Model,Elements}=__studio;Save.dirty=()=>{};Save.flush=async()=>true;UI.syncToolbar=()=>{};__studio.Gutter.reset=()=>{};__studio.Gutter.update=()=>{};const s=Model.newStory();s.kind='poetry';const v=Model.newVolume(s),c=Model.newChapter(s);v.chapters=[c];s.volumes=[v];App.story=s;UI.mode='write';UI.applyKind();await Ed.load({id:c.id,storyId:s.id,html:'<p data-pid="verse_1">A long opening line with enough words to demonstrate that wrapping stays identical across every screen width and every reading device.</p><p data-pid="verse_2" style="text-align:center"><b>Second stanza stays beside its decoration.</b><br>Another carefully spaced line.</p>'});document.querySelector('#viewLibrary').classList.remove('on');document.querySelector('#viewStudio').classList.add('on');document.querySelector('#writeArea').hidden=false;Elements.insert({src:'/assets/elements/mock-leaf.svg',w:22,x:64});Elements.update({x:64,y:7,rotation:25,opacity:65,mode:'behind'});Elements.clear();return {html:Ed.serialize(),layout:Elements.layout};});
assert.equal(saved.layout.canvas.width,640);
const geometry=()=>page.evaluate(()=>{const root=__studio.Ed.el,r=root.getBoundingClientRect();return {width:r.width,text:Array.from(root.querySelectorAll('p')).map(p=>{const b=p.getBoundingClientRect();return {id:p.dataset.pid,x:b.x-r.x,y:b.y-r.y,w:b.width,h:b.height,text:p.textContent};}),element:__studio.Elements.figures().map(f=>{const b=f.querySelector('img').getBoundingClientRect();return {x:b.x-r.x,y:b.y-r.y,w:b.width,h:b.height};})};});
const authored=await geometry();await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{__studio.UI.applyMode();__studio.UI.syncViewport();__studio.Elements.render();});assert.deepEqual(await geometry(),authored,'writer canvas reflowed on mobile');
// Same saved HTML and renderer in the writer's actual preview.
await page.evaluate(()=>{__studio.UI.previewWidth='phone';__studio.UI.renderPreview();});assert.equal(await page.locator('#preview .je-design-controls').count(),1);
const reader=await context.newPage();let readerHTML=fs.readFileSync(path.join(root,'reader-demo.html'),'utf8').replace('boot();\n\n})();','window.__reader={renderPost};\n\n})();');
await reader.route('**/*',async route=>{const u=new URL(route.request().url());if(u.pathname==='/reader-demo.html')return route.fulfill({contentType:'text/html',body:readerHTML});if(u.pathname==='/config.js')return route.fulfill({body:"window.JOURNAL_CONFIG={SUPABASE_URL:'https://example.test',SUPABASE_ANON_KEY:'test'};"});if(u.hostname==='cdn.jsdelivr.net')return route.fulfill({body:'window.supabase={createClient:()=>({})};'});if(u.pathname.endsWith('.svg'))return route.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"><rect width="100" height="100" fill="green"/></svg>'});const file=path.join(root,u.pathname);if(u.pathname.startsWith('/assets/')&&fs.existsSync(file))return route.fulfill({contentType:file.endsWith('.css')?'text/css':'application/javascript',body:fs.readFileSync(file,'utf8')});return route.abort();});
reader.on('pageerror',e=>errors.push(e.message));await reader.goto('https://studio.test/reader-demo.html');await reader.evaluate(saved=>{const post={id:'test-post',kind:'poem',type:'Poetry',title:'Designed poem',bodyMd:saved.html,author:'Author',username:'author',tags:[],comments:[],likes:0,date:'Today',read:'1 min',avatarColorHex:'#abcdef',grad:'linear-gradient(red,blue)',isOwn:true};const node=__reader.renderPost(post);document.querySelector('#app').replaceChildren(node);},saved);
for(const width of [1200,768,390,320]){
 await reader.setViewportSize({width,height:850});await reader.waitForFunction(()=>document.querySelector('.je-design-output')?.dataset.designScale);
 await reader.evaluate(()=>JournalDesign.refresh(document.querySelector('.je-design-host')));await reader.waitForTimeout(50);
 const read=await reader.evaluate(()=>{const root=document.querySelector('.je-design-output'),r=root.getBoundingClientRect(),scale=Number(root.dataset.designScale);return {width:r.width/scale,text:Array.from(root.querySelectorAll('p')).map(p=>{const b=p.getBoundingClientRect();return {id:p.dataset.pid,x:(b.x-r.x)/scale,y:(b.y-r.y)/scale,w:b.width/scale,h:b.height/scale,text:p.textContent};}),element:Array.from(root.querySelectorAll('.journal-element img')).map(img=>{const b=img.getBoundingClientRect();return {x:(b.x-r.x)/scale,y:(b.y-r.y)/scale,w:b.width/scale,h:b.height/scale};}),scale};});
 assert(Math.abs(read.width-authored.width)<1);for(let i=0;i<authored.text.length;i++)for(const key of ['x','y','w','h'])assert(Math.abs(read.text[i][key]-authored.text[i][key])<2,`${width} paragraph ${i} ${key} moved`);for(const key of ['x','y','w','h'])assert(Math.abs(read.element[0][key]-authored.element[0][key])<2,`${width} element ${key} moved`);
 // Core's asynchronous refresh must not calculate geometry against an already scaled canvas.
 await reader.evaluate(()=>JournalElements.refresh());await reader.waitForTimeout(40);
}
// Page-turn transforms on an ancestor must not alter saved layout geometry.
const beforeTurn=await reader.evaluate(()=>{const root=document.querySelector('.je-design-output');return {height:root.style.getPropertyValue('--je-page-height'),elements:Array.from(root.querySelectorAll('.journal-element')).map(f=>[f.style.top,f.style.left,f.style.width])};});await reader.evaluate(()=>{document.querySelector('.je-design-host').style.transform='perspective(1000px) rotateY(35deg)';JournalElements.refresh();});await reader.waitForTimeout(50);const duringTurn=await reader.evaluate(()=>{const root=document.querySelector('.je-design-output');return {height:root.style.getPropertyValue('--je-page-height'),elements:Array.from(root.querySelectorAll('.journal-element')).map(f=>[f.style.top,f.style.left,f.style.width])};});assert.deepEqual(duringTurn,beforeTurn,'page-turn transform changed element coordinates');await reader.evaluate(()=>document.querySelector('.je-design-host').style.transform='');
await reader.getByRole('button',{name:'Reading view',exact:true}).click();assert(await reader.locator('.je-reading-output').isVisible());assert.equal(await reader.locator('.je-reading-output .journal-element').count(),0);assert((await reader.locator('.je-reading-output').textContent()).includes('Second stanza'));await reader.getByRole('button',{name:'Original layout',exact:true}).click();const initialScale=await reader.locator('.je-design-output').getAttribute('data-design-scale');await reader.getByRole('button',{name:'Zoom in',exact:true}).click();await reader.waitForTimeout(40);assert(Number(await reader.locator('.je-design-output').getAttribute('data-design-scale'))>Number(initialScale));await reader.getByRole('button',{name:'Fit page',exact:true}).click();
// Long-form works reject new Elements; existing decorations still survive save/reload.
await page.evaluate(async html=>{const {Ed,App,Elements}=__studio;App.story.kind='journal';await Ed.load({id:Ed.chapterId,storyId:Ed.storyId,html});const count=Elements.items.size;if(Elements.allowed()||Elements.insert({src:'/assets/elements/mock-leaf.svg'})!==false)throw Error('long-form elements enabled');if(Elements.items.size!==count||!Ed.serialize().includes('mock-leaf'))throw Error('legacy decoration lost');},saved.html);
assert.equal(errors.length,0,errors.join('\n'));console.log('Fixed design: writer and real reader geometry preserved at 1200/768/390/320px; view modes, zoom, preview, category gating and legacy preservation passed.');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
