const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const html=fs.readFileSync('reader-demo.html','utf8'),start=html.indexOf('function compareWorkOrder('),end=html.indexOf('async function loadNeighbors(',start);
const id=n=>'00000000-0000-0000-0000-'+String(n).padStart(12,'0');
function reader(journals,works){
 const seen=[];const context={console,categoryById:n=>({name:{1:'Journals',2:'Stories',3:'Poetry',6:'Articles'}[n],color:'red'}),supabaseClient:{from(table){let rows=(table==='journals'?journals:works).slice(),ascending;const query={select(){return query;},eq(key,value){rows=rows.filter(r=>r[key]===value);return query;},in(key,values){rows=rows.filter(r=>values.includes(r[key]));return query;},or(filter){seen.push({table,filter});const match=filter.match(/^published_at\.(lt|gt)\.(.+),and\(published_at.eq\.(.+),id\.(lt|gt)\.(.+)\)$/);assert(match,filter);const older=match[1]==='lt',at=Date.parse(match[2]);rows=rows.filter(r=>older?Date.parse(r.published_at)<at||Date.parse(r.published_at)===at&&r.id<match[5]:Date.parse(r.published_at)>at||Date.parse(r.published_at)===at&&r.id>match[5]);return query;},order(key,opt){if(key==='published_at')ascending=opt.ascending;return query;},limit(){rows.sort((a,b)=>(ascending?1:-1)*context.compareWorkOrder(a,b));return Promise.resolve({data:rows.slice(0,1)});}};return query;}}};
 vm.createContext(context);vm.runInContext(html.slice(start,end),context);return {...context,seen};
}
const row=(n,at,fields={})=>({id:id(n),published_at:at,title:'work',status:'published',visibility:'public',category_id:3,profiles:{username:'author'},...fields});
test('reader turns between standalone and structured categories in feed order',async()=>{const r=reader([row(1,'2026-10-04T10:00:00Z'),row(5,'2026-10-04T06:00:00Z')],[row(2,'2026-10-04T09:00:00Z',{kind:'journal'}),row(3,'2026-10-04T08:00:00Z',{kind:'story',status:'ongoing'}),row(4,'2026-10-04T07:00:00Z',{kind:'article',status:'completed'})]);let post={id:id(1),publishedAt:'2026-10-04T10:00:00Z'};for(const expected of ['Journals','Stories','Articles','Poetry']){const next=await r.fetchAdjacentRef(post,1);assert.equal(next.type,expected);post={id:next.id,publishedAt:next.publishedAt};}assert.equal((await r.fetchAdjacentRef(post,-1)).type,'Articles');assert.equal(await r.fetchAdjacentRef(post,1),null);});
test('equal timestamps use IDs without skipping, looping, or exposing drafts',async()=>{const at='2026-10-04T10:00:00Z',r=reader([row(1,at)],[row(2,at,{kind:'story'}),row(4,at,{kind:'article',status:'draft'}),row(5,at,{kind:'journal',visibility:'private'})]);const next=await r.fetchAdjacentRef({id:id(3),publishedAt:at},1);assert.equal(next.id,id(2));assert.equal((await r.fetchAdjacentRef({id:id(1),publishedAt:at},-1)).id,id(2));assert.equal(await r.fetchAdjacentRef({id:id(3),publishedAt:at},-1),null);assert(r.seen.every(q=>q.filter.includes(',and(')));});
test('cross-table ordering retains sub-millisecond publication precision',()=>{const r=reader([],[]);assert(r.compareWorkOrder(row(1,'2026-10-04T10:00:00.123900Z'),row(2,'2026-10-04T10:00:00.123100Z'))>0);});
