// Offline Chromium regression suite. Install Playwright and run: node tests/writer-elements.browser.cjs
const {chromium}=require('playwright');
const fs=require('fs');const assert=require('assert');const path=require('path');const root=path.join(__dirname,'..');
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE?{executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE}:{})});const context=await browser.newContext({viewport:{width:1200,height:900}});const page=await context.newPage();let errors=[];page.on('pageerror',e=>errors.push(e.message));
let html=fs.readFileSync(path.join(root,'writer-studio.html'),'utf8');const boot=html.indexOf('(async function boot()');html=html.slice(0,boot)+"window.__studio={RemoteStore,CONFIG,Sim,Ed,App,UI,Store,Save,Model,Sanitize,Images,Elements,Tools,Dock,Panel,Gutter};\n})();\n</script></body></html>";
await page.route('**/*',async route=>{let url=new URL(route.request().url());if(url.pathname==='/writer-studio.html')return route.fulfill({contentType:'text/html',body:html});if(url.pathname==='/config.js')return route.fulfill({body:"window.JOURNAL_CONFIG={SUPABASE_URL:'https://example.test',SUPABASE_ANON_KEY:'test'};"});if(url.pathname.includes('supabase'))return route.fulfill({body:'window.supabase={createClient:()=>({})};'});let f={'/assets/elements.js':'elements.js','/assets/elements-editor.js':'elements-editor.js','/assets/elements.css':'elements.css','/assets/writer-drafts.js':'writer-drafts.js'}[url.pathname];if(f)return route.fulfill({contentType:f.endsWith('.css')?'text/css':'application/javascript',body:fs.readFileSync(path.join(root,'assets',f),'utf8')});if(url.pathname.endsWith('.svg'))return route.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"><rect width="100" height="100" fill="green"/></svg>'});return route.abort();});
await page.goto('https://studio.test/writer-studio.html');await page.waitForFunction(()=>window.__studio);
await page.evaluate(async()=>{
 const {RemoteStore:R,Store,App,Model,CONFIG,Ed,UI,Save}=__studio;CONFIG.ownerId='author-one';
 Save.dirty=()=>{};Save.flush=async()=>true;UI.syncToolbar=()=>{};UI.updateTreeMeta=()=>{};UI.infoVisible=()=>false;UI.renderTree=()=>{};UI.syncCrumb=()=>{};__studio.Gutter.reset=()=>{};__studio.Gutter.update=()=>{};
 const s=Model.newStory();s.kind='journal';s.structure='single';s.status='published';s.title='Public title';s.description='Public description';s.coverImageId='__url:https://images.test/public.jpg';const v=Model.newVolume(s),c=Model.newChapter(s);c.id=s.id;c.status='published';c.title=s.title;c.publishedAt=1000;v.chapters=[c];s.volumes=[v];
 window.publicStory=structuredClone(s);window.publicChapter={id:s.id,storyId:s.id,html:'<p>Public text</p>',published:{html:'<p>Public text</p>',at:1000,title:s.title}};window.remoteWrites=[];
 R.get=async(kind,id)=>structuredClone(kind==='stories'?window.publicStory:kind==='chapters'?window.publicChapter:undefined);
 R.all=async(kind)=>kind==='stories'?[structuredClone(window.publicStory)]:[];
 R.put=async(kind,value)=>{window.remoteWrites.push(kind);if(kind==='stories')window.publicStory=structuredClone(value);if(kind==='chapters')window.publicChapter=structuredClone(value);return value;};
 R.del=async(kind,id)=>window.remoteWrites.push('delete:'+kind);
 R.publishSingle=async(story,rec)=>{window.remoteWrites.push('publish');if(window.failPublish)throw Error('Injected publication failure');window.publicStory=structuredClone(story);window.publicChapter=structuredClone(rec);if(window.concurrentDraft){const later={...rec,html:'<p>Concurrent edit</p>'};await Store.put('chapters',later);}};
 App.story=await Store.get('stories',s.id);App.rec=await Store.get('chapters',s.id);await Ed.load({id:s.id,storyId:s.id,html:App.rec.html});UI.mode='write';
});
await page.evaluate(async()=>{const {App,Store,Ed}=__studio;App.story.title='Private title';App.story.description='Private description';App.story.tags=['private-tag'];await App.persistStory();await App.persistChapter({chapterId:Ed.chapterId,storyId:Ed.storyId,html:'<p>Private text <b>formatting</b></p>',pidSeq:10,words:4,chars:20,at:Date.now()});App.storyPersistSoon.cancel();});
assert.equal(await page.evaluate(()=>window.remoteWrites.length),0,'autosave made remote writes');assert.equal(await page.evaluate(()=>window.publicStory.title),'Public title');assert.equal(await page.evaluate(()=>window.publicChapter.html),'<p>Public text</p>');
await page.evaluate(async()=>{const {Store,App,Ed}=__studio;App.story=await Store.get('stories',App.story.id);const rec=await Store.get('chapters',Ed.chapterId);if(!rec.html.includes('Private text')||rec.published.html!=='<p>Public text</p>')throw Error('draft/published isolation');const rows=await Store.all('stories');if(rows[0].title!=='Private title')throw Error('library draft lost');__studio.Save.setState('saved');if(!document.querySelector('#saveStatus').textContent.includes('on this device'))throw Error('local label missing');});
// A second tab loads the same persistent IndexedDB draft without modifying the public copy.
const saved=await page.evaluate(()=>({story:window.publicStory,chapter:window.publicChapter}));const second=await page.context().newPage();
// The route belongs to the original page, so install it on the second tab before loading.
await second.route('**/*',async route=>{const url=new URL(route.request().url());if(url.pathname==='/writer-studio.html')return route.fulfill({contentType:'text/html',body:html});if(url.pathname==='/config.js')return route.fulfill({body:"window.JOURNAL_CONFIG={SUPABASE_URL:'https://example.test',SUPABASE_ANON_KEY:'test'};"});if(url.pathname.includes('supabase'))return route.fulfill({body:'window.supabase={createClient:()=>({})};'});const file=url.pathname.startsWith('/assets/')&&path.join(root,url.pathname);if(file&&fs.existsSync(file))return route.fulfill({contentType:file.endsWith('.css')?'text/css':'application/javascript',body:fs.readFileSync(file,'utf8')});return route.abort();});await second.goto('https://studio.test/writer-studio.html');
await second.evaluate(async saved=>{const {CONFIG,Store,RemoteStore:R,App}=__studio;CONFIG.ownerId='author-one';R.get=async kind=>kind==='stories'?saved.story:saved.chapter;App.story=await Store.get('stories',saved.story.id);const rec=await Store.get('chapters',saved.chapter.id);if(App.story.title!=='Private title'||!rec.html.includes('Private text'))throw Error('persistent draft missing');CONFIG.ownerId='author-two';const other=await Store.get('stories',saved.story.id);if(other.title!=='Public title')throw Error('cross-account draft leak');},saved);await second.close();
// Republish failure retains the saved text/details; success promotes them once.
await page.evaluate(async()=>{const {App,Store}=__studio;window.failPublish=true;try{await Store.publish(App.story,[App.story.id]);throw Error('publication should fail');}catch(e){if(e.message==='publication should fail')throw e;}const rec=await Store.get('chapters',App.story.id);if(!rec.html.includes('Private text'))throw Error('failed publication discarded draft');window.failPublish=false;App.story=await Store.publish(App.story,[App.story.id]);});
assert.equal(await page.evaluate(()=>window.publicStory.title),'Private title');assert(await page.evaluate(()=>window.publicChapter.published.html.includes('Private text')));assert.equal(await page.evaluate(async()=>!!await __studio.Store.drafts.get('chapters',__studio.App.story.id)),false);
// New edits remain local after republishing. Edits during publication are not removed.
await page.evaluate(async()=>{const {App,Store}=__studio;let rec=await Store.get('chapters',App.story.id);rec.html='<p>Next private edit</p>';await Store.put('chapters',rec);window.concurrentDraft=true;await Store.publish(App.story,[App.story.id]);window.concurrentDraft=false;rec=await Store.get('chapters',App.story.id);if(rec.html!=='<p>Concurrent edit</p>')throw Error('concurrent draft was lost');});
// Local covers never upload until explicit publication, and public cover removal is deferred.
await page.evaluate(async()=>{const {Images,App,Store}=__studio;const rec=await Images.upload({type:'story_cover',storyId:App.story.id,blob:new Blob(['test'],{type:'image/jpeg'}),width:3,height:2});if(!rec.id.startsWith('__local:'))throw Error('cover uploaded before republish');const stored=await Store.drafts.get('images',rec.id);if(!stored.value.blob.size)throw Error('cover blob was not persisted');App.story.coverImageId=rec.id;await App.persistStory();Images.cache.clear();const reloaded=await Images.record(rec.id);if(!reloaded.public_url.startsWith('blob:'))throw Error('local cover reload failed');});
// Cover blobs upload at the explicit boundary; backup downloads retain local text and cover data.
await page.evaluate(async()=>{const {App,Store,Images}=__studio;let uploads=0;const original=Images.upload;Images.upload=async options=>{if(!options.forceRemote)throw Error('cover publication missing explicit flag');uploads++;const rec={id:'uploaded-cover',public_url:'https://images.test/new-cover.jpg'};Images.cache.set(rec.id,rec);return rec;};await Store.publish(App.story,[App.story.id]);if(uploads!==1||window.publicStory.coverImageId!=='uploaded-cover')throw Error('local cover was not promoted');Images.upload=original;});
const backup=await Promise.all([page.waitForEvent('download'),page.evaluate(()=>__studio.App.downloadDraft())]);const backupPath=await backup[0].path();const backupJSON=JSON.parse(fs.readFileSync(backupPath,'utf8'));assert(backupJSON.chapters.some(c=>c.html));assert(backupJSON.covers.some(c=>c.data.startsWith('data:image/jpeg;base64,')));
// A storage failure never falls through to remote saving.
await page.evaluate(async()=>{const {Store,App}=__studio;const put=Store.drafts.put,before=window.remoteWrites.length;Store.drafts.put=async()=>{throw Error('Injected quota error');};try{await Store.put('chapters',{id:App.story.id,storyId:App.story.id,html:'Quota test',published:{html:'Public'}});throw Error('save should fail');}catch(e){if(e.message==='save should fail')throw e;}finally{Store.drafts.put=put;}if(window.remoteWrites.length!==before)throw Error('storage failure leaked draft');});
// Multipart bodies, metadata and structure all stay local; whole-work republish promotes published chapters.
await page.evaluate(async()=>{const {App,Store,RemoteStore:R,Model}=__studio;const s=Model.newStory();s.kind='journal';s.structure='multiple';s.status='published';const v=Model.newVolume(s),a=Model.newChapter(s);a.status='published';v.chapters=[a];s.volumes=[v];const b=Model.newChapter(s);b.status='published';v.chapters.push(b);const records=new Map([a,b].map(c=>[c.id,{id:c.id,storyId:s.id,html:'Old '+c.id,published:{html:'Old '+c.id,at:1000}}]));let writes=0;
 R.get=async(kind,id)=>structuredClone(kind==='stories'?s:records.get(id));R.put=async(kind,value)=>{writes++;if(kind==='chapters')records.set(value.id,structuredClone(value));return value;};App.story=await Store.get('stories',s.id);for(const c of [a,b]){const rec=await Store.get('chapters',c.id);rec.html='Draft '+c.id;await Store.put('chapters',rec);}App.story.title='Local multipart';await Store.put('stories',App.story);if(writes)throw Error('multipart draft reached public tables');await Store.publish(App.story,[a.id]);if(![...records.values()].every(r=>r.published.html.startsWith('Draft ')))throw Error('whole-work republish missed chapter');
 // Unpublished works retain the original cloud save path.
 const fresh=Model.newStory();fresh.kind='journal';fresh.structure='single';App.story=fresh;const before=writes;await Store.put('stories',fresh);if(writes!==before+1)throw Error('new draft cloud saving changed');
});
assert.equal(errors.length,0,errors.join('\n'));console.log('Device drafts: public isolation, persistence, account boundaries, publication failure/concurrency, local covers, multipart and original draft saves passed.');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
