// Offline Chromium regression suite. Install Playwright and run: node tests/writer-elements.browser.cjs
const {chromium}=require('playwright');
const fs=require('fs');const assert=require('assert');const path=require('path');const root=path.join(__dirname,'..');
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE?{executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE}:{})});const page=await browser.newPage({viewport:{width:1200,height:900}});let errors=[];page.on('pageerror',e=>errors.push(e.message));
let html=fs.readFileSync(path.join(root,'writer-studio.html'),'utf8');const boot=html.indexOf('(async function boot()');html=html.slice(0,boot)+"window.__studio={Ed,App,UI,Store,Save,Model,Sanitize,Images,Elements,Tools,Dock,Panel,Gutter};\n})();\n</script></body></html>";
await page.route('**/*',async route=>{let url=new URL(route.request().url());if(url.pathname==='/writer-studio.html')return route.fulfill({contentType:'text/html',body:html});if(url.pathname==='/config.js')return route.fulfill({body:"window.JOURNAL_CONFIG={SUPABASE_URL:'https://example.test',SUPABASE_ANON_KEY:'test'};"});if(url.pathname.includes('supabase'))return route.fulfill({body:'window.supabase={createClient:()=>({})};'});let f={'/assets/elements.js':'elements.js','/assets/elements-editor.js':'elements-editor.js','/assets/elements.css':'elements.css','/assets/writer-drafts.js':'writer-drafts.js','/assets/design-view.js':'design-view.js'}[url.pathname];if(f)return route.fulfill({contentType:f.endsWith('.css')?'text/css':'application/javascript',body:fs.readFileSync(path.join(root,'assets',f),'utf8')});if(url.pathname.endsWith('.svg'))return route.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"><rect width="100" height="100" fill="green"/></svg>'});return route.abort();});
await page.goto('https://studio.test/writer-studio.html');await page.waitForFunction(()=>window.__studio);
const result=await page.evaluate(async()=>{const {Ed,App,UI,Store,Save,Model,Images,Elements}=window.__studio;window.__studio.Gutter.reset=()=>{};window.__studio.Gutter.update=()=>{};Save.dirty=()=>{};Save.flush=async()=>true;UI.syncToolbar=()=>{};
let calls=0;const story=Model.newStory();story.kind='story';story.title='Story';const journal=Model.newStory();journal.kind='journal';journal.title='Journal';
Store.all=async()=>{calls++;return [story,journal];};Images.url=()=>new Promise(()=>{});story.coverImageId='slow-cover';
UI.kind='story';await UI.renderLibrary();if(document.querySelectorAll('#libGrid .card').length!==2)throw Error('cards blocked by cover');UI.kind='journal';await UI.renderLibrary(false);UI.kind='story';await UI.renderLibrary(false);if(calls!==1)throw Error('tab refetched');await UI.renderLibrary();if(calls!==2)throw Error('refresh failed');
story.kind='poetry';App.story=story;App.locked=()=>false;UI.mode='write';UI.kind='story';const chapter=Model.all(story)[0];if(!chapter){const v=Model.newVolume(story);v.chapters.push(Model.newChapter(story));story.volumes.push(v);}const ch=Model.all(story)[0].chapter;await Ed.load({id:ch.id,storyId:story.id,html:'<p data-pid="paragraph_001">First paragraph with text.</p><p data-pid="paragraph_002">Second paragraph stays intact.</p><p data-pid="paragraph_003">Third paragraph.</p>'});
document.querySelector('#viewLibrary').classList.remove('on');document.querySelector('#viewStudio').classList.add('on');document.querySelector('#writeArea').hidden=false;const p=Ed.el.querySelector('p');Ed.placeCaret(p,false);window.savedP=Ed.el.querySelectorAll('p')[1];
Elements.insert({src:'/assets/elements/mock-leaf.svg',mode:'front',x:10,y:5,w:20,ratio:1});Elements.panel?.remove();Elements.panel=null;window.elementId=JournalElements.model(Elements.chosen()[0]).id;
return {calls,hasElement:Elements.chosen().length,preserved:window.savedP===Ed.el.querySelector('[data-pid=paragraph_002]'),html:Ed.el.innerHTML};});console.log('Library cache, cover loading and element insertion passed');assert(result.hasElement===1);assert(result.preserved);assert.equal(errors.length,0,errors.join('\n'));
async function state(){return page.evaluate(()=>{const {Elements,Ed}=__studio;let f=Elements.figures().find(f=>JournalElements.model(f).id===window.elementId);const r=f.querySelector('img').getBoundingClientRect();return {m:JournalElements.model(f),rect:{x:r.x,y:r.y,w:r.width,h:r.height},preserved:window.savedP===Ed.el.querySelector('[data-pid=paragraph_002]'),text:Ed.el.textContent};});}
async function gesture(kind,dx,dy){return page.evaluate(({kind,dx,dy})=>{const {Elements}=__studio;let f=Elements.figures().find(f=>JournalElements.model(f).id===window.elementId);Elements.selected=new Set([window.elementId]);const r=f.querySelector('img').getBoundingClientRect(),e={pointerId:1,clientX:r.right,clientY:r.bottom,preventDefault(){}};Elements.begin(e,kind);Elements.movePointer({...e,clientX:e.clientX+dx,clientY:e.clientY+dy});const ghost=f.querySelector('img').getBoundingClientRect();Elements.endPointer({...e});Elements.panel?.remove();Elements.panel=null;return ghost?{x:ghost.x,y:ghost.y,w:ghost.width,h:ghost.height}:null;},{kind,dx,dy});}
await page.evaluate(()=>__studio.Elements.setLayout({snap:false}));let a=await state();let ghost=await gesture('move',42,68),b=await state();assert(Math.abs(b.rect.x-a.rect.x-42)<1);assert(Math.abs(b.rect.y-a.rect.y-68)<1);assert(b.preserved);
await page.evaluate(()=>__studio.Ed.cmd('undo'));let undo=await state();assert(Math.abs(undo.rect.x-a.rect.x)<1);await page.evaluate(()=>__studio.Ed.cmd('redo'));assert(Math.abs((await state()).rect.x-b.rect.x)<1);
a=await state();await gesture('se',0,70);b=await state();assert(b.m.w>a.m.w);
for(const mode of ['front','behind']){await page.evaluate(mode=>{__studio.Elements.selected=new Set([window.elementId]);__studio.Elements.update({mode,rotation:0,x:10,y:0,w:20,placed:false,offsetX:0,offsetY:0});},mode);a=await state();ghost=await gesture('move',30,25);b=await state();assert.equal(b.m.mode,mode);assert(Math.abs(b.rect.x-a.rect.x-30)<2,mode+' x drift');assert(Math.abs(b.rect.y-a.rect.y-25)<2,mode+' y drift');}

// Rotate each corner in local coordinates; ghost and final geometry must coincide.
for(const angle of [0,45,90,-35])for(const corner of ['nw','ne','sw','se']){
 await page.evaluate(angle=>{const {Elements}=__studio;Elements.selected=new Set([window.elementId]);Elements.update({mode:'front',rotation:angle,w:20,ratio:1,x:35,y:40,aspect:true,anchor:'paragraph'});},angle);
 a=await state();ghost=await gesture(corner,corner.includes('w')?-18:18,corner.includes('n')?-24:24);b=await state();
 for(const key of ['x','y','w','h'])assert(Math.abs(ghost[key]-b.rect[key])<2.5,`${angle} ${corner} ${key} preview drift: ${ghost[key]} / ${b.rect[key]}`);
}
console.log('16 rotated corner checks passed');
// Text and element models survive clean serialization, sanitizer, and reload.
const snap=await page.evaluate(()=>{const {Ed,Elements,Sanitize}=__studio;const html=Ed.serialize();const fragment=Sanitize.toFragment(html,{keepIds:true});let div=document.createElement('div');div.append(fragment);return {html,clean:div.innerHTML,m:JournalElements.model(div.querySelector('.journal-element')),text:div.textContent};});
assert(!snap.html.includes('data-je-transaction'));assert.equal(snap.m.id,await page.evaluate(()=>window.elementId));assert(snap.text.includes('Second paragraph stays intact.'));assert.equal(snap.m.rotation,-35);
await page.evaluate(html=>{const {Ed}=__studio;return Ed.load({id:Ed.chapterId,storyId:Ed.storyId,html});},snap.clean);console.log('serialization and sanitizer passed');
// Fixed pages and margins.
await page.evaluate(()=>{const {Elements}=__studio;Elements.selected=new Set([window.elementId]);Elements.setLayout({mode:'page',margin:20});Elements.update({mode:'front',anchor:'page',page:2,x:15,y:10,w:20,rotation:0});});
a=await state();ghost=await gesture('move',27,41);b=await state();assert(Math.abs(b.rect.x-a.rect.x-27)<2);assert(Math.abs(b.rect.y-a.rect.y-41)<2);
// Cancellation has no commit and releases all drag UI.
await page.evaluate(()=>{const {Elements}=__studio;const f=Elements.chosen()[0],r=f.querySelector('img').getBoundingClientRect();Elements.begin({pointerId:9,clientX:r.x,clientY:r.y},'move');Elements.movePointer({pointerId:9,clientX:r.x+25,clientY:r.y+20,preventDefault(){}});window.dispatchEvent(new Event('resize'));if(Elements.gesture||document.querySelector('.je-drag-ghost'))throw Error('cancel cleanup');});
// Mobile responsive layout uses the same underlying model.
await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{__studio.UI.applyMode();__studio.UI.syncViewport();});await page.evaluate(()=>{const {Elements}=__studio;Elements.selected=new Set([window.elementId]);Elements.setLayout({mode:'flow'});Elements.update({mode:'front',anchor:'paragraph',rotation:0,x:15,y:10,w:20});});
a=await state();ghost=await gesture('move',20,35);b=await state();assert(Math.abs(b.rect.x-a.rect.x-20)<2);assert(Math.abs(b.rect.y-a.rect.y-35)<2);console.log('mobile placement passed');
// Native keyboard undo/redo, then ordinary typing must keep the element intact.
a=await state();await page.evaluate(()=>__studio.Ed.restoreFocus());await page.keyboard.press('Control+z');b=await state();assert(Math.abs(b.rect.x-a.rect.x)>5,'keyboard undo did nothing');await page.keyboard.press('Control+Shift+z');assert(Math.abs((await state()).rect.x-a.rect.x)<2,'keyboard redo');
await page.evaluate(()=>{const {Elements,Ed}=__studio;Elements.clear();Ed.placeCaret(Ed.el.querySelector('[data-pid=paragraph_002]'),false);});await page.keyboard.type(' More text.');assert((await state()).text.includes(' More text.'));console.log('keyboard undo/redo and typing passed');
// Duplicate, lock, deletion, and their history.
await page.evaluate(()=>{const {Elements}=__studio;Elements.selected=new Set([window.elementId]);Elements.duplicate();});assert.equal(await page.evaluate(()=>__studio.Elements.figures().length),2);
await page.evaluate(()=>{const {Elements}=__studio;Elements.update({locked:true},{includeLocked:true});const before=Elements.figures().length;Elements.remove();if(Elements.figures().length!==before)throw Error('locked deletion');Elements.update({locked:false},{includeLocked:true});Elements.remove();});assert.equal(await page.evaluate(()=>__studio.Elements.figures().length),1);
await page.evaluate(()=>__studio.Ed.cmd('undo'));assert.equal(await page.evaluate(()=>__studio.Elements.figures().length),2);await page.evaluate(()=>__studio.Ed.cmd('redo'));assert.equal(await page.evaluate(()=>__studio.Elements.figures().length),1);console.log('duplicate, locking, deletion history passed');

await page.evaluate(()=>{const {Elements}=__studio;Elements.selected=new Set(Elements.figures().map(f=>JournalElements.model(f).id));Elements.duplicate();});

// Multi-selection spacing is preserved even at a horizontal boundary.
await page.evaluate(()=>{const {Elements}=__studio;const all=Elements.figures();Elements.selected=new Set(all.map(f=>JournalElements.model(f).id));Elements.update(m=>({mode:'front',anchor:'paragraph',x: m.id===window.elementId?10:50,y:m.id===window.elementId?10:60,w:15}));});
const groupBefore=await page.evaluate(()=>__studio.Elements.chosen().map(f=>{const r=f.querySelector('img').getBoundingClientRect();return {id:JournalElements.model(f).id,x:r.x,y:r.y,mode:JournalElements.model(f).mode}}));
await page.evaluate(()=>{const {Elements}=__studio;const r=Elements.chosen()[0].querySelector('img').getBoundingClientRect();const e={pointerId:44,clientX:r.x,clientY:r.y};Elements.begin(e,'move');Elements.movePointer({...e,clientX:r.x+999,clientY:r.y+30,preventDefault(){}});Elements.endPointer(e);});
const groupAfter=await page.evaluate(()=>__studio.Elements.chosen().map(f=>{const r=f.querySelector('img').getBoundingClientRect();return {id:JournalElements.model(f).id,x:r.x,y:r.y,mode:JournalElements.model(f).mode}}));
if(groupBefore.length===2){assert(Math.abs((groupAfter[1].x-groupAfter[0].x)-(groupBefore[1].x-groupBefore[0].x))<2);assert(Math.abs((groupAfter[1].y-groupAfter[0].y)-(groupBefore[1].y-groupBefore[0].y))<2);}
console.log('group boundary movement passed');
// Direct mouse and touch gestures must not focus text, scroll, or open settings.
await page.setViewportSize({width:1200,height:900});
await page.evaluate(()=>{const {Elements,Ed}=__studio;Elements.clear();Elements.arranging=true;Elements.selected=new Set([window.elementId]);Elements.update({anchor:'page',page:1,x:20,y:5,w:20,rotation:0,mode:'behind'});Elements.setLayout({snap:false});Elements.clear();Elements.syncHits();document.activeElement?.blur();window.focusCount=0;Ed.el.addEventListener('focus',()=>window.focusCount++);});
const paras=()=>page.evaluate(()=>Array.from(__studio.Ed.el.querySelectorAll('p')).map(p=>({html:p.outerHTML,x:p.getBoundingClientRect().x,y:p.getBoundingClientRect().y})));
const beforeParas=await paras(),scrollBefore=await page.evaluate(()=>document.querySelector('#scroller').scrollTop);
a=await state();await page.mouse.move(a.rect.x+a.rect.w/2,a.rect.y+a.rect.h/2);await page.mouse.down();await page.mouse.move(a.rect.x+a.rect.w/2+38,a.rect.y+a.rect.h/2+32,{steps:8});await page.mouse.up();b=await state();assert(Math.abs(b.rect.x-a.rect.x-38)<2);assert(Math.abs(b.rect.y-a.rect.y-32)<2);
assert.deepEqual(await paras(),beforeParas);assert.equal(await page.evaluate(()=>window.focusCount),0);assert.equal(await page.evaluate(()=>document.querySelector('#scroller').scrollTop),scrollBefore);assert.equal(await page.locator('.je-panel').count(),0);
const cdp=await page.context().newCDPSession(page);a=await state();const tx=a.rect.x+a.rect.w/2,ty=a.rect.y+a.rect.h/2;
await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:tx,y:ty}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:tx+24,y:ty+45}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});b=await state();assert(Math.abs(b.rect.x-a.rect.x-24)<2);assert(Math.abs(b.rect.y-a.rect.y-45)<2);assert.equal(await page.evaluate(()=>window.focusCount),0);assert.equal(await page.evaluate(()=>document.querySelector('#scroller').scrollTop),scrollBefore);assert.deepEqual(await paras(),beforeParas);
// Layer and style edits keep both paragraph geometry and DOM identity.
await page.evaluate(()=>{const {Elements,Ed}=__studio;window.savedP=Ed.el.querySelector('[data-pid=paragraph_002]');Elements.order('bottom');Elements.update({x:18,opacity:55,flipX:true,border:2});Elements.order('top');Elements.order('bottom');});assert.deepEqual(await paras(),beforeParas);assert((await state()).preserved);assert.equal((await state()).m.mode,'behind');
// Every member of a group moves, rotates, and undoes together.
await page.evaluate(()=>{const {Elements}=__studio;Elements.selected=new Set(Array.from(Elements.items.keys()));Elements.update(m=>({rotation:0,x:m.id===window.elementId?10:50,y:m.id===window.elementId?20:60,w:15,anchor:'page',page:1}));Elements.group();Elements.panel?.remove();Elements.panel=null;});
const models=()=>page.evaluate(()=>Array.from(__studio.Elements.items.values()));const grouped=await models();
await page.evaluate(()=>{const E=__studio.Elements,r=E.imageBox(E.chosen()[0]),e={pointerId:88,clientX:r.left,clientY:r.top};E.begin(e,'move');E.movePointer({...e,clientX:r.left+40,clientY:r.top+30,preventDefault(){}});E.endPointer(e);});const movedGroup=await models();assert(movedGroup.every((m,i)=>m.x!==grouped[i].x));await page.evaluate(()=>__studio.Elements.undo());assert.deepEqual(await models(),grouped);await page.evaluate(()=>__studio.Elements.redo());assert.deepEqual(await models(),movedGroup);
await page.evaluate(()=>{const E=__studio.Elements,boxes=E.chosen().map(f=>E.imageBox(f)),cx=(Math.min(...boxes.map(r=>r.left))+Math.max(...boxes.map(r=>r.right)))/2,cy=(Math.min(...boxes.map(r=>r.top))+Math.max(...boxes.map(r=>r.bottom)))/2,e={pointerId:89,clientX:cx+100,clientY:cy};E.begin(e,'rotate');E.movePointer({...e,clientX:cx,clientY:cy+100,preventDefault(){}});E.endPointer(e);});const rotatedGroup=await models();assert(rotatedGroup.every(m=>m.rotation===90));assert(rotatedGroup.some((m,i)=>m.x!==movedGroup[i].x||m.y!==movedGroup[i].y));assert(Math.abs((rotatedGroup[1].x-rotatedGroup[0].x)+(movedGroup[1].y-movedGroup[0].y))<.1);assert(Math.abs((rotatedGroup[1].y-rotatedGroup[0].y)-(movedGroup[1].x-movedGroup[0].x))<.1);await page.evaluate(()=>__studio.Elements.undo());assert.deepEqual(await models(),movedGroup);
// Snap state, unlocked ratio bounds, cancellation, and mixed text history.
await page.evaluate(()=>{const E=__studio.Elements;E.setLayout({snap:true});E.setLayout({snap:false});E.undo();if(!E.snap||!E.layout.snap)throw Error('snap history out of sync');E.redo();E.selected=new Set([window.elementId]);E.update({aspect:false,ratio:1,w:20,x:20,y:10});});ghost=await gesture('se',0,1000);b=await state();for(const key of ['x','y','w','h'])assert(Math.abs(ghost[key]-b.rect[key])<2.5,'unlocked ratio preview mismatch');
const beforeText=await page.evaluate(()=>__studio.Ed.el.textContent);await page.evaluate(()=>{const {Ed,Elements}=__studio;Elements.clear();Elements.arranging=false;Elements.syncHits();Ed.placeCaret(Ed.el.querySelector('p'),false);Ed.restoreFocus();});await page.keyboard.type('Typed text.');assert((await state()).text.includes('Typed text.'));await page.keyboard.press('Control+z');assert.equal((await state()).text,beforeText);await page.keyboard.press('Control+Shift+z');assert((await state()).text.includes('Typed text.'));assert.equal(await page.evaluate(()=>__studio.Ed.el.querySelectorAll('.journal-element').length),0);
// HTML paste of a decoration imports into the independent surface and undoes atomically.
const pasteCount=await page.evaluate(()=>__studio.Elements.items.size);await page.evaluate(()=>{const {Ed,Elements}=__studio;const html=JournalElements.make(document,Elements.items.values().next().value).outerHTML;Ed.onPaste({preventDefault(){},clipboardData:{getData:type=>type==='text/html'?html:''}});});assert.equal(await page.evaluate(()=>__studio.Elements.items.size),pasteCount+1);assert.equal(await page.evaluate(()=>__studio.Ed.el.querySelectorAll('.journal-element').length),0);await page.evaluate(()=>__studio.Elements.undo());assert.equal(await page.evaluate(()=>__studio.Elements.items.size),pasteCount);
// Serialize and reload through the actual editor lifecycle; saved decorations remain outside text.
const finalSave=await page.evaluate(()=>({html:__studio.Ed.serialize(),models:Array.from(__studio.Elements.items.values()),layout:__studio.Elements.layout,text:__studio.Ed.el.textContent,paragraphs:__studio.Ed.el.querySelectorAll('p').length}));await page.evaluate(async saved=>{const {Ed}=__studio;await Ed.load({id:Ed.chapterId,storyId:Ed.storyId,html:saved.html});},finalSave);assert.deepEqual(await models(),finalSave.models);assert.equal(await page.evaluate(()=>__studio.Ed.el.querySelectorAll('p').length),finalSave.paragraphs);assert.equal(await page.evaluate(()=>__studio.Ed.el.textContent),finalSave.text);assert.equal(await page.evaluate(()=>__studio.Ed.el.querySelectorAll('.journal-element').length),0);assert.deepEqual(await page.evaluate(()=>__studio.Elements.layout),finalSave.layout);
// Reader/preview hydration preserves saved widths and layer bands.
await page.evaluate(()=>{const {Ed,Elements}=__studio,box=document.createElement('div');box.id='reader-test';box.style.cssText='position:absolute;left:0;top:0;width:'+Ed.el.getBoundingClientRect().width+'px;box-sizing:border-box;padding:'+getComputedStyle(Ed.el).padding+';';box.innerHTML=Ed.serialize();document.body.append(box);JournalElements.hydrate(box);for(const f of box.querySelectorAll('.journal-element')){const m=JournalElements.model(f),r=f.querySelector('img').getBoundingClientRect(),live=Elements.nodes.get(m.id).querySelector('img').getBoundingClientRect();if(Math.abs(r.width-live.width)>2||Math.abs(r.height-live.height)>2)throw Error('saved preview size drift');const text=box.querySelector('p');if(m.mode==='behind'&&Number(getComputedStyle(f).zIndex)>=Number(getComputedStyle(text).zIndex))throw Error('behind text layer');}box.remove();window.dispatchEvent(new Event('beforeprint'));window.dispatchEvent(new Event('afterprint'));});
// Ordinary formatting, paragraph insertion and plain-text paste remain undoable.
await page.evaluate(()=>{const {Ed,Elements}=__studio;Elements.clear();Elements.arranging=false;Elements.syncHits();Ed.restoreFocus();const p=Ed.el.querySelector('p'),r=document.createRange();r.selectNodeContents(p);const sel=getSelection();sel.removeAllRanges();sel.addRange(r);Ed.saveSel();Ed.cmd('bold');if(!p.querySelector('b,strong,[style*=font-weight]'))throw Error('formatting failed');});await page.keyboard.press('Control+z');await page.keyboard.press('Control+Shift+z');
await page.evaluate(()=>{const Ed=__studio.Ed;Ed.placeCaret(Ed.el.querySelector('p'),false);Ed.restoreFocus();});const beforeEnter=await page.evaluate(()=>__studio.Ed.el.innerHTML);await page.keyboard.press('Enter');await page.keyboard.type('New paragraph.');await page.keyboard.press('Control+z');await page.keyboard.press('Control+z');assert.equal(await page.evaluate(()=>__studio.Ed.el.innerHTML),beforeEnter);
await page.evaluate(()=>__studio.Ed.onPaste({preventDefault(){},clipboardData:{getData:t=>t==='text/plain'?'Plain pasted text':''}}));assert((await state()).text.includes('Plain pasted text'));await page.keyboard.press('Control+z');assert(!(await state()).text.includes('Plain pasted text'));
await page.evaluate(()=>{const {Elements,App}=__studio;const before=JSON.stringify(Array.from(Elements.items.values()));App.locked=()=>true;Elements.insert({src:'/assets/elements/mock-leaf.svg'});Elements.update({x:99});Elements.remove();Elements.undo();if(JSON.stringify(Array.from(Elements.items.values()))!==before)throw Error('locked chapter was modified');App.locked=()=>false;});
console.log('direct mouse/touch, text isolation, groups, mixed history and save/reload passed');

// Simultaneous loads share one request; stale completion cannot clear the newer tab.
await page.evaluate(async()=>{const {App,UI,Store,Model}=__studio;App.libraryCache=null;let resolve,count=0;Store.all=()=>{count++;return new Promise(r=>resolve=r)};UI.kind='story';const first=UI.renderLibrary(false);UI.kind='journal';const second=UI.renderLibrary(false);const s=Model.newStory();s.kind='journal';s.title='Latest journal';resolve([s]);await Promise.all([first,second]);if(count!==1||!document.querySelector('#libGrid').textContent.includes('Latest journal'))throw Error('tab loading race');});
console.log('library concurrency passed');
console.log('errors',errors);assert.equal(errors.length,0,errors.join('\n'));await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
